services:
#  nginx:
#    container_name: nginx
#    build:
#      dockerfile: ./DockerfileNginx
#      context: .
#    volumes:
#      - ./:/var/www/e4y:rw
#      - ./nginx/api.e4y.local_nginx.crt:/etc/pki/ca-trust/source/anchors/api.e4y.local.crt:rw
#      - ./nginx/api.e4y.local.key:/etc/pki/ca-trust/source/anchors/api.e4y.local.key:rw
#      - ./nginx/shared.conf.d/:/etc/nginx/conf.d/shared.conf.d:rw
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
#      - ./nginx/10-api-e4y-local.conf:/etc/nginx/conf.d/10-api-e4y-local.conf:rw
#      - $SSH_AUTH_SOCK:/ssh-agent
#    environment:
#      SSH_AUTH_SOCK: /ssh-agent
#      EF_USER: ${USER}
#    ports:
#      - "443:443"
#      - "80:80"
#    depends_on:
#      - e4y_php83
#      - e4y_postgres
  e4y_php83:
    user: "e4y:e4y"
    container_name: e4y_php83
    build:
      dockerfile: ./DockerfilePHP83
      context: .
      args:
        GID: 1000
        UID: 1000
        HEMANUSER: e4y
        HEMANGROUP: e4y
    volumes:
      - ./:/var/www/e4y:rw
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
      - $SSH_AUTH_SOCK:/ssh-agent
      - $HOME/.ssh/known_hosts:/home/e4y/.ssh/known_hosts:rw
      - $HOME/.ssh/config:/home/e4y/.ssh/config:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_IDE_CONFIG: "serverName=php83"
  e4y_postgres:
    image: postgres:15.1
    container_name: e4y_postgres
    command: -c shared_buffers=512MB -c max_connections=200 -c work_mem=50MB -c maintenance_work_mem=256MB
    tmpfs:
      - /tmp/test/:rw,noexec,nosuid,size=50m
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_USER=e4y
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=e4y
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    volumes:
      - ./database/dump:/tmp/dump:ro
      - ./database/data:/var/lib/postgresql/data:rw
      - ./database/log:/var/log/postgresql:rw
    ports:
      - "5432:5432"
