kalendarz:
    resource:
        path: ../src/Kalendarz/Ports/Rest
        namespace: App\Kalendarz\Ports\Rest
    type: attribute

courses:
    resource:
        path: ../src/Courses/Ports/Rest
        namespace: App\Courses\Ports\Rest
    type: attribute