kalendarz:
    resource:
        path: ../src/Kalendarz/Ports/Rest
        namespace: App\Kalendarz\Ports\Rest
    type: attribute

szkolenia:
    resource:
        path: ../src/Szkolenia/Ports/Rest
        namespace: App\Szkolenia\Ports\Rest
    type: attribute